feign:
  client:
    config:
      default:
        loggerLevel: FULL
spring:
  cache:
    cache-names: portOneTokenCache
    caffeine:
      spec: maximumSize=100,expireAfterWrite=1700s # 30분마다 갱신
---
spring:
  config:
    activate:
      on-profile: dev
---
spring:
  config:
    activate:
      on-profile: local
---
spring:
  config:
    activate:
      on-profile: prod
