feign:
  client:
    config:
      default:
        loggerLevel: FULL
logging:
  level:
    com.example.matchinfrastructure.aligo.client.KakaoAligoFeignClient: DEBUG
---
spring:
  config:
    activate:
      on-profile: dev
---
spring:
  config:
    activate:
      on-profile: local
---
spring:
  config:
    activate:
      on-profile: prod
