server:
  host: ${SERVER_HOST}

oauth:
  kakao:
    base-url: ${KAKAO_BASE_URL}
    client-id: ${KAKAO_CLIENT}
    client-secret: ${KAKAO_SECRET}
    redirect-url: ${KAKAO_REDIRECT}
    app-id: ${KAKAO_APP_ID}
    admin-key: ${KAKAO_ADMIN_KEY}
  naver:
    secret: ${NAVER_SECRET}
    client: ${NAVER_CLIENT}
    redirect-url: ${NAVER_REDIRECT}

jwt:
  header: X-AUTH-TOKEN
  secret: ${JWT_SECRET_KEY}
  refresh: ${JWT_REFRESH_KEY}
  access-token-seconds: 1
  refresh-token-seconds: 30
sms:
  secret: ${SMS_SECRET_KEY}
  api: ${SMS_API_KEY}
  sender: ${SMS_SENDER}

##배포시 prod, dev 구분
nice:
  secret: ${NICE_SECRET_KEY}
  client: ${NICE_CLIENT_KEY}
  url: ${NICE_URL}
  mid: ${NICE_MID}
  key: ${NICE_KEY}

aws:
  access-key: ${AWS_ACCESS_KEY}
  secret-key: ${AWS_SECRET_KEY}
  s3:
    bucket: ${AWS_S3_BUCKET}
    base-url: ${AWS_S3_BASE_URL}

discord:
  webhook:
    error: ${DISCORD_WEBHOOK_ERROR}
    alert: ${DISCORD_WEBHOOK_ALERT}

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: official.match.kr@gmail.com
    password: ${APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    auth-code-expiration-millis: 1800000  # 30 * 60 * 1000 == 30분

aligo:
  username: ${ALIGO_USERNAME}
  key: ${ALIGO_KEY}
  sender: ${SMS_SENDER}
  sender-key: ${KAKAO_SENDER_KEY}}

web:
  return:
    url: ${RETURN_URL}

match:
  aligo:
    url: ${MATCH_ALIGO_URL}

portone:
  code: ${PORTONE_CODE}
  key: ${PORTONE_KEY}
  secret: ${PORTONE_SECRET}
  billmid: ${PORTONE_BILL_MID}

private:
  aes:
    key: ${AES_PRIVATE_KEY}

apple:
  key:
    path: ${APPLE_KEY_PATH}
  bundle:
    id: ${APPLE_BUNDLE_ID}
  team:
    id: ${APPLE_TEAM_ID}
