server:
  port: 9000

spring:
  profiles:
    include:
      - infrastructure
      - domain
      - common
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 300MB
    mvc:
      pathmatch:
        matching-strategy: ant_path_matcher


---
spring:
  profiles:
    active:
      - dev

---
spring:
  profiles:
    active:
      - prod

---
spring:
  profiles:
    active:
      - local
