server:
  port: 9000

spring:
  datasource:
    url: ${DB_URL_HOST}
    username: ${AWS_DB_USER_NAME}
    password: ${AWS_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    include:
      - infrastructure
      - domain
      - common
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 300MB
    mvc:
      pathmatch:
        matching-strategy: ant_path_matcher


---
spring:
  profiles:
    active:
      - dev

---
spring:
  profiles:
    active:
      - prod

---
spring:
  profiles:
    active:
      - local
