server:
  port: 9000
spring:
  profiles:
    include:
      - domain
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 300MB
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
jwt:
  header: X-AUTH-TOKEN
  secret: ${JWT_SECRET_KEY}
  refresh: ${JWT_REFRESH_KEY}
  access-token-seconds: 31536000
  refresh-token-seconds: 31536000
