name: prod MATCH API Server CI/CD

on:
  push:
    branches: [aligo]
    #tags:
    # - Dev-Api-v*.*.*
  workflow_dispatch: # 수동 실행 옵션 (생략)

jobs:
  build:
    runs-on: ubuntu-latest # action 스크립트가 작동될 OS

    steps: # 작업 단계
      - name: Checkout source code #  단계별 이름, 구분자로 소스를 가져옴
        uses: actions/checkout@v2

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'



      - name: Set Environment - Common Prod Yml
        uses: microsoft/variable-substitution@v1
        with:
          files: ./Match-Common/src/main/resources/application-common.yml
        env:
          oauth.kakao.base-url: ${{ secrets.KAKAO_PROD_BASE_URL }}
          oauth.kakao.client-id: ${{ secrets.KAKAO_CLIENT }}
          oauth.kakao.client-secret: ${{ secrets.KAKAO_SECRET }}
          oauth.kakao.redirect-url: ${{ secrets.KAKAO_PROD_REDIRECT }}
          oauth.kakao.app-id: ${{ secrets.KAKAO_APP_ID }}
          oauth.kakao.admin-key: ${{ secrets.KAKAO_ADMIN_KEY }}
          jwt.secret: ${{ secrets.JWT_SECRET_KEY }}
          jwt.refresh: ${{ secrets.JWT_REFRESH_KEY }}
          oauth.naver.secret: ${{ secrets.NAVER_SECRET }}
          oauth.naver.client: ${{ secrets.NAVER_CLIENT }}
          oauth.naver.redirect-url: ${{ secrets.NAVER_PROD_REDIRECT}}
          sms.secret: ${{ secrets.SMS_SECRET_KEY }}
          sms.api: ${{ secrets.SMS_API_KEY }}
          sms.sender: ${{ secrets.SMS_SENDER }}
          nice.secret: ${{ secrets.NICE_PROD_SECRET_KEY}}
          nice.client: ${{ secrets.NICE_PROD_CLIENT_KEY }}
          nice.url: ${{ secrets.NICE_PROD_URL}}
          aws.access-key: ${{ secrets.AWS_S3_ACCESS_KEY }}
          aws.secret-key: ${{ secrets.AWS_S3_SECRET_KEY }}
          aws.s3.bucket: ${{ secrets.AWS_S3_BUCKET }}
          aws.s3.bucket-url: ${{ secrets.AWS_S3_BASE_URL }}
          discord.webhook.error: ${{ secrets.DISCORD_WEBHOOK_ERROR}}
          discord.webhook.alert: ${{ secrets.DISCORD_WEBHOOK_ALERT }}
          server.host: ${{ secrets.DEV_SERVER_HOST}}
          spring.password: ${{ secrets.APP_PASSWORD}}
          web.return.url: ${{ secrets.PROD_RETURN_URL }}
          match.aligo.url: ${ secrets.MATCH_ALIGO_URL }}



      - name: Set Environment Domain - Domain Prod Yml
        uses: microsoft/variable-substitution@v1
        with:
          files: ./Match-Domain/src/main/resources/application-domain-prod.yml
        env:
          spring.datasource.url: ${{ secrets.PROD_DB_URL_HOST }}
          spring.datasource.username: ${{ secrets.AWS_DB_USER_NAME }}
          spring.datasource.password: ${{ secrets.AWS_DB_PASSWORD }}
          spring.redis.host : ${{ secrets.REDIS_PROD_HOST }}

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

      - name: Build with Gradle
        run: ./gradlew Match-Api:bootJar
        shell: bash

      - name: Get current time
        uses: 1466587594/get-current-time@v2
        id: current-time
        with:
          format: YYYYMMDDTHHmm
          utcOffset: "+09:00"

      - name: Generate deployment packagez
        run: |
          mkdir -p deploy
          cp Match-Aligo/build/libs/*.jar deploy/match-aligo-api.jar
          cp Procfile deploy/Procfile
          cp -r .ebextensions-aligo deploy/.ebextensions
          cp -r .platform deploy/.platform
          cd deploy && zip -r match-aligo-api-${{steps.current-time.outputs.formattedTime}}-${{github.sha}} .

      - name: Deploy Consumer to EB
        uses: einaregilsson/beanstalk-deploy@v19
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: MatchAligoServer
          environment_name: MatchAligoServer-env
          version_label: match-aligo-api-${{steps.current-time.outputs.formattedTime}}-${{github.sha}}
          region: ap-northeast-2
          deployment_package: deploy/match-aligo-api-${{steps.current-time.outputs.formattedTime}}-${{github.sha}}.zip
          wait_for_deployment: false
