name: dev MATCH API Server CI/CD

on:
  pull_request:
    on: deploytest
      #tags:
    # - Dev-Api-v*.*.*
  workflow_dispatch: # 수동 실행 옵션 (생략)

jobs:
  build:
    runs-on: ubuntu-latest # action 스크립트가 작동될 OS

    steps: # 작업 단계
      - name: Checkout source code # 단계별 이름, 구분자로 소스를 가져옴
        uses: actions/checkout@v2

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: set Environment - Api Yml
        uses: microsoft/variable-substitution@v1
        with:
          files: ./Match-Api/src/main/resources/application-api.yml
        env:
          jwt.secret: ${{ secrets.JWT_SECRET_KEY }}
          jwt.refresh: ${{ secrets.JWT_REFRESH_KEY }}

      - name: set Environment - Domain Yml
        uses: microsoft/variable-substitution@v1
        with:
          files: ./Match-Domain/src/main/resources/application-domain.yml
        env:
          spring.datasource.url: ${{ secrets.DEV_DB_URL_HOST }}
          spring.datasource.username: ${{ secrets.AWS_DB_USER_NAME }}
          spring.datasource.password: ${{ secrets.AWS_DB_PASSWORD }}

      - name: Grant execute permission for gradlew
        working-directory: ./server-app
        run: chmod +x ./gradlew
        shell: bash

      - name: Build with Gradle
        working-directory: ./server-app
        run: ./gradlew Match-Api:bootJar
        shell: bash

      - name: Get current time
        uses: 1466587594/get-current-time@v2
        id: current-time
        with:
          format: YYYYMMDDTHHmm
          utcOffset: "+09:00"

      - name: Generate deployment package
        run: |
          mkdir -p deploy
          cp Match-Api/build/libs/*.jar deploy/match-api.jar
          cp Procfile deploy/Procfile
          cp -r .ebextensions deploy/.ebextensions
          cp -r .platform deploy/.platform
          cd deploy && zip -r deploy.zip .

      - name: Deploy Consumer to EB
        uses: einaregilsson/beanstalk-deploy@v19
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: match
          environment_name: Match-env
          version_label: match-server-api-${{steps.current-time.outputs.formattedTime}}-${{github.sha}}
          region: ap-northeast-2
          deployment_package: deploy/match-server-api-${{steps.current-time.outputs.formattedTime}}-${{github.sha}}.zip
